language: cpp
compiler: g++
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-6
      - cmake-data
      - cmake
      - libcurl-dev
before_install:
  - export CXX="g++-6"
  - cd ./third-party/c-ares/; cmake -DCARES_STATIC=ON .; make; cd -
  - cd ./third-party/libevent/; cmake .; make; cd -
  - cd ./third-party/jsoncpp/; cmake .; make; cd -
install:
script: cmake . && make
